apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
  labels:
    app: reactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app : reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: 015813010/reactapp
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name:  reactapp
spec:
  type: NodePort
  selector:
    app:  reactapp
  ports:
    - port:  80
      targetPort:  3000
      nodePort: 30009