server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: https://eurekaservicefoodfix.herokuapp.com/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes: 
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: sale-service
          uri: lb://sale-service
          predicates:
            - Path=/sale/**

