apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: diegohuapayarivera/order-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---
kind: Service
apiVersion: v1
metadata:
  name:  order-service-svc
spec:
  type: NodePort
  selector:
    app:  order-service-app
  ports:
    - port:  80
      targetPort:  8001
      nodePort: 30007