server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: microservice
          uri: https://github.com/diegohuapayarivera/foodfix
          search-paths: config-data
  application:
    name: config-service